import type { DashboardPreviewData } from "../dashboard/DashboardClient";
import type { ActivePlanView } from "../dashboard/page";

// Isolated examples, never loaded from a customer or sent to account APIs.
export const SAMPLE_PLAN: ActivePlanView = {
  id: "preview-plan",
  currentDay: 3,
  startDate: "2026-09-13",
  endDate: "2026-09-19",
  daysRemaining: 5,
  isDigital: false,
  status: "active",
  calorieTarget: 2000,
  proteinTarget: 100,
  mealPlan: {
    id: "preview-menu",
    name: "Sample vegetarian week",
    displayName: "Sample vegetarian week",
    slug: "",
    tier: "STANDARD",
    category: "BALANCED",
    dietaryVariant: "VEG",
    avgCaloriesPerDay: 2000,
    cycleLengthDays: 7,
  },
};

export const SAMPLE_DAY: DashboardPreviewData = {
  meals: [
    {
      slotId: "sample-breakfast",
      mealSlot: "BREAKFAST",
      label: "Breakfast",
      time: "8:00 am",
      emoji: "",
      dayNumber: 3,
      isLogged: true,
      isSkipped: false,
      recipe: {
        id: "sample-chilla",
        name: "Moong dal chilla with green chutney",
        caloriesPerServing: 420,
        proteinGrams: 24,
        carbsGrams: 54,
        fatGrams: 12,
        imageUrl:
          "/images/ai/recipes/maharashtrian-moong-dal-chilla-with-green.webp",
      },
    },
    {
      slotId: "sample-lunch",
      mealSlot: "LUNCH",
      label: "Lunch",
      time: "12:30 pm",
      emoji: "",
      dayNumber: 3,
      isLogged: false,
      isSkipped: false,
      recipe: {
        id: "sample-cauliflower",
        name: "Chettinad cauliflower steak",
        caloriesPerServing: 580,
        proteinGrams: 26,
        carbsGrams: 74,
        fatGrams: 20,
        imageUrl:
          "/images/ai/recipes/chettinad-cauliflower-steak-with-black-pepper.webp",
      },
    },
    {
      slotId: "sample-snack",
      mealSlot: "SNACK",
      label: "Snack",
      time: "4:30 pm",
      emoji: "",
      dayNumber: 3,
      isLogged: false,
      isSkipped: false,
      recipe: {
        id: "sample-makhana",
        name: "Makhana chaat with tamarind chutney",
        caloriesPerServing: 300,
        proteinGrams: 12,
        carbsGrams: 44,
        fatGrams: 8,
        imageUrl:
          "/images/ai/recipes/rajasthani-makhana-chaat-with-tamarind-chutney.webp",
      },
    },
    {
      slotId: "sample-dinner",
      mealSlot: "DINNER",
      label: "Dinner",
      time: "7:30 pm",
      emoji: "",
      dayNumber: 3,
      isLogged: false,
      isSkipped: false,
      recipe: {
        id: "sample-paneer",
        name: "Palak paneer with jowar roti",
        caloriesPerServing: 700,
        proteinGrams: 38,
        carbsGrams: 80,
        fatGrams: 25,
        imageUrl:
          "/images/ai/recipes/north-indian-palak-paneer-with-jowar.webp",
      },
    },
  ],
  balance: {
    caloriesIn: 420,
    caloriesOut: 0,
    net: 420,
    target: 2000,
    remaining: 1580,
    status: "under",
    mealsLogged: 1,
    mealsTotal: 4,
    proteinIn: 24,
    proteinTarget: 100,
  },
  workout: {
    hasWorkout: true,
    isRestDay: false,
    scheduleName: "Sample training",
    focusArea: "Full-body strength",
    estimatedCalories: 180,
    durationMins: 25,
    completedToday: false,
    exercises: [
      {
        exerciseId: "sample-squat",
        name: "Bodyweight squat",
        sets: 3,
        reps: 12,
        durationSecs: null,
        restSecs: 60,
        notes: null,
      },
      {
        exerciseId: "sample-pushup",
        name: "Incline push-up",
        sets: 3,
        reps: 10,
        durationSecs: null,
        restSecs: 60,
        notes: null,
      },
      {
        exerciseId: "sample-plank",
        name: "Plank",
        sets: 3,
        reps: null,
        durationSecs: 30,
        restSecs: 60,
        notes: null,
      },
    ],
  },
  consistency: {
    score: 75,
    label: "Building a routine",
    meals: { logged: 9, delivered: 12 },
    workouts: { completed: 2, scheduled: 3 },
  },
};
